import { useEffect } from 'react';
import { HelpPage, applyTheme, resolveTheme } from '@boriskulakhmetov-aidigital/design-system';
import '@boriskulakhmetov-aidigital/design-system/style.css';

const GUIDE = `# Prompt Engineering Assistant — User Guide

**Tool:** [Prompt Engineering Assistant](https://prompt-engineer.apps.aidigitallabs.com)

The Prompt Engineering Assistant helps you craft, test, and refine AI prompts. Whether you're building prompts for ChatGPT, Gemini, Claude, or any other AI tool, this assistant ensures your prompts are clear, consistent, and optimized for the best results.

---

## Getting Started

### 1. Sign In

Open the app and sign in with your AIDigital Labs account.

### 2. Describe the Prompt You Need

Tell the AI what you want your prompt to accomplish. Be as specific as you can about the desired output. For example:

- "I need a prompt that generates product descriptions for e-commerce"
- "Help me write a prompt for summarizing customer feedback"
- "Create a prompt that writes social media captions in our brand voice"

### 3. Answer Follow-Up Questions

The AI will ask clarifying questions to understand exactly what you need:

- What tone should the output have?
- How long should the output be?
- Are there any constraints or required elements?
- Can you share an example of a good output?

> **Tip:** The more examples and context you provide, the better the engineered prompt will be.

### 4. Review the Engineered Prompt

The AI designs a structured prompt and tests it for you. You'll see:

- **The prompt itself** — ready to copy and use
- **Test results** — sample outputs generated by the prompt
- **Variations** — alternative versions for different use cases

### 5. Copy and Use

Once you're happy with the prompt, copy it directly from the interface and paste it into your AI tool of choice.

---

## What to Expect

| Step | Time |
|------|------|
| Describe what you need | 1–2 minutes |
| AI questions and refinement | 2–5 minutes |
| Prompt generation and testing | 30–60 seconds |
| **Total** | **4–8 minutes** |

---

## Tips

- **Start with the end in mind.** Before you begin, think about what a perfect output looks like. Share that vision with the AI.

- **Iterate freely.** If the first version isn't quite right, tell the AI what to adjust. "Make the tone more formal" or "Add a section for pricing" — the AI refines on the fly.

- **Test across models.** A prompt that works well in ChatGPT might need tweaks for Gemini. Mention which AI you're targeting.

- **Save for later.** Your sessions are preserved automatically, so you can revisit and refine prompts anytime.

- **Use dark mode** if you prefer a darker interface. Click the theme toggle in the top-right corner.

---

## Your Past Sessions

Every session is saved automatically. Use the sidebar to browse your previous prompt engineering sessions.
`;

export default function AppHelpPage() {
  useEffect(() => { applyTheme(resolveTheme()); }, []);
  return <HelpPage markdown={GUIDE} />;
}
